- name: variables
  hosts: localhost
  vars: #variable declaration
    Course: "Terraform"
    Trainer: "prashanth"
    Duration: "2 months"
  tasks:
  - name: print information
    ansible.builtin.debug:
      msg: "Hi , im prepariung for {{Course}} at coaching center {{Trainer}} course time is {{Duration}}."