- name: varibles
  hosts: web
  vars: #variable declaration
    Course: "TERRAFORM"
    Trainer: "PRASHANTH"
    Duration: "2 MONTHS"
  tasks:
  - name: Print overide information
    vars: # task level varaible
      Course: "DEVOPS"
    ansible.builtin.debug:
      msg: "Hi, i'm learning {{Course}} by trainer called {{Trainer}} the duration is {{Duration}}."

  - name: print information
    ansible.builtin.debug:
      msg: "Hi, We are learning {{Course}} from Trainer {{Trainer}}, Duration is {{Duration}}."
