- name: varaibles from inventory 
  hosts: localhost
  tasks:
  - name: print information
    vars:
    ansible.builtin.debug:
      msg: "Hi, We are learning {{Course}} from Trainer {{Trainer}}, Duration is {{Duration}}."