- name: data types
  hosts: localhost
  vars:
    vars:
      Course: Devops with AWS  #sTRING
      Tools: #list
      - SHELL
      - ANSIBLE
      - TERRAFORM
      - DOCKER
      - JENKINS

    Experience: #map or dictionary
      Devops: 3
      AWS: 2
      DOCKER: 1
    Realtimeproject: true  # boolean
  tasks: 
  - name: print variables
    ansible.builtin.debug:
      msg: "Course: {{Course}}, Tools covered: {{Tools}}, Experience is: {{Experience}}, is real project: {{RealProject}}"
   