- name: default value
  hosts: web
  tasks:
  - name: print default value
    ansible.builtin.debug:
      msg: "hello {{course | default('ansible') }}"
  
  - name: upper case
    hosts: web
    vars:
      greetings: "hello bunny How are you ?"
    tasks:  
    - name: convert into uppercase
      ansible.builtin.debug:
       msg: "{{greetings | upper}}"

  - name: lower case
    hosts: web
    vars: 
      greetings: "HELLO PRASHANTH HOW ARE YOU ?"
    tasks:
    - name: convert inti lowercase
      ansible,builtin.debug:
        msg: "{{greetings | lower }}"   

        