- name: install and nginx
  hosts: web
  become: yes  # equal to -b in adhoc commands, getting root access
  tasks:
  - name: install nginx
    ansible.builtin.dnf:
      name: nginx
      state: latest
  - name: install git 
    ansible.builtin.dnf:
      name: git
      state: latest
  - name: start nginx
    ansible.builtin.service:    # service means it will show wheather it is started or not
      name: nginx
      state: started
      enabled: yes
  - name: start git
    ansible.builtin.service:    # service means it will show wheather it is started or not
      name: git
      state: started
      enabled: yes      